apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes/nginx
    targetRevision: controller-v1.10.0
    path: deploy/static/provider/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
