apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}